# Generated by Django 4.1.3 on 2023-02-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Father_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('village', models.CharField(max_length=30)),
                ('mobile_no', models.IntegerField()),
            ],
        ),
    ]
